server:
  port: 80

spring:
  application:
    name: consumer-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: consumer80
    prefer-ip-address: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

PROVIDER-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule